-- Migration 003 — one-time tasks / events.
-- A "pinned" block is placed once at a fixed time and is never moved or
-- regenerated by the weekly re-plan. One-time things (meetings, reminders) are
-- pinned blocks; manually setting a block's start time also pins it.
alter table scheduled_blocks add column if not exists pinned boolean not null default false;
